version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda123"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ip6wl8bq0a5k"
s3_prefix = "lambda123"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "apiGatewayStageName=dev lambdaFunctionName=MeghFlow-function"

